/**
 * Remote Flags API
 * Remote Flags openapi definition. Public readonly API for integration with Remote Flags.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@remoteflags.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UsageRequestsPerMonth from './UsageRequestsPerMonth';

/**
 * The Usage model module.
 * @module com.remoteflags.model/Usage
 * @version 1.0.7
 */
class Usage {
    /**
     * Constructs a new <code>Usage</code>.
     * @alias module:com.remoteflags.model/Usage
     * @param requests {Number} Returned sum of requests
     * @param requestsPerMonth {Array.<module:com.remoteflags.model/UsageRequestsPerMonth>} Requests per month
     */
    constructor(requests, requestsPerMonth) { 
        
        Usage.initialize(this, requests, requestsPerMonth);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requests, requestsPerMonth) { 
        obj['requests'] = requests;
        obj['requestsPerMonth'] = requestsPerMonth;
    }

    /**
     * Constructs a <code>Usage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.remoteflags.model/Usage} obj Optional instance to populate.
     * @return {module:com.remoteflags.model/Usage} The populated <code>Usage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Usage();

            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], 'Number');
            }
            if (data.hasOwnProperty('requestsPerMonth')) {
                obj['requestsPerMonth'] = ApiClient.convertToType(data['requestsPerMonth'], [UsageRequestsPerMonth]);
            }
        }
        return obj;
    }


}

/**
 * Returned sum of requests
 * @member {Number} requests
 */
Usage.prototype['requests'] = undefined;

/**
 * Requests per month
 * @member {Array.<module:com.remoteflags.model/UsageRequestsPerMonth>} requestsPerMonth
 */
Usage.prototype['requestsPerMonth'] = undefined;






export default Usage;

