/**
 * Remote Flags API
 * Remote Flags openapi definition. Public readonly API for integration with Remote Flags.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@remoteflags.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsageRequestInner model module.
 * @module com.remoteflags.model/UsageRequestInner
 * @version 1.0.9
 */
class UsageRequestInner {
    /**
     * Constructs a new <code>UsageRequestInner</code>.
     * @alias module:com.remoteflags.model/UsageRequestInner
     * @param flagId {String} 
     * @param date {String} 
     * @param flagProperties {Object} 
     */
    constructor(flagId, date, flagProperties) { 
        
        UsageRequestInner.initialize(this, flagId, date, flagProperties);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, flagId, date, flagProperties) { 
        obj['flagId'] = flagId;
        obj['date'] = date;
        obj['flagProperties'] = flagProperties;
    }

    /**
     * Constructs a <code>UsageRequestInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.remoteflags.model/UsageRequestInner} obj Optional instance to populate.
     * @return {module:com.remoteflags.model/UsageRequestInner} The populated <code>UsageRequestInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsageRequestInner();

            if (data.hasOwnProperty('flagId')) {
                obj['flagId'] = ApiClient.convertToType(data['flagId'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('flagProperties')) {
                obj['flagProperties'] = ApiClient.convertToType(data['flagProperties'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} flagId
 */
UsageRequestInner.prototype['flagId'] = undefined;

/**
 * @member {String} date
 */
UsageRequestInner.prototype['date'] = undefined;

/**
 * @member {Object} flagProperties
 */
UsageRequestInner.prototype['flagProperties'] = undefined;






export default UsageRequestInner;

