/**
 * Remote Flags API
 * Remote Flags openapi definition. Public readonly API for integration with Remote Flags.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@remoteflags.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsageRequestsPerMonth model module.
 * @module com.remoteflags.model/UsageRequestsPerMonth
 * @version 1.0.7
 */
class UsageRequestsPerMonth {
    /**
     * Constructs a new <code>UsageRequestsPerMonth</code>.
     * @alias module:com.remoteflags.model/UsageRequestsPerMonth
     * @param year {Number} 
     * @param month {Number} 
     * @param requests {Number} 
     */
    constructor(year, month, requests) { 
        
        UsageRequestsPerMonth.initialize(this, year, month, requests);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, year, month, requests) { 
        obj['year'] = year;
        obj['month'] = month;
        obj['requests'] = requests;
    }

    /**
     * Constructs a <code>UsageRequestsPerMonth</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.remoteflags.model/UsageRequestsPerMonth} obj Optional instance to populate.
     * @return {module:com.remoteflags.model/UsageRequestsPerMonth} The populated <code>UsageRequestsPerMonth</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsageRequestsPerMonth();

            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('month')) {
                obj['month'] = ApiClient.convertToType(data['month'], 'Number');
            }
            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} year
 */
UsageRequestsPerMonth.prototype['year'] = undefined;

/**
 * @member {Number} month
 */
UsageRequestsPerMonth.prototype['month'] = undefined;

/**
 * @member {Number} requests
 */
UsageRequestsPerMonth.prototype['requests'] = undefined;






export default UsageRequestsPerMonth;

