/**
 * Remote Flags API
 * Remote Flags openapi definition. Public readonly API for integration with Remote Flags.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@remoteflags.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RemoteflagsNodejsClient);
  }
}(this, function(expect, RemoteflagsNodejsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RemoteflagsNodejsClient.UsageRequestInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsageRequestInner', function() {
    it('should create an instance of UsageRequestInner', function() {
      // uncomment below and update the code to test UsageRequestInner
      //var instance = new RemoteflagsNodejsClient.UsageRequestInner();
      //expect(instance).to.be.a(RemoteflagsNodejsClient.UsageRequestInner);
    });

    it('should have the property flagId (base name: "flagId")', function() {
      // uncomment below and update the code to test the property flagId
      //var instance = new RemoteflagsNodejsClient.UsageRequestInner();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new RemoteflagsNodejsClient.UsageRequestInner();
      //expect(instance).to.be();
    });

    it('should have the property flagProperties (base name: "flagProperties")', function() {
      // uncomment below and update the code to test the property flagProperties
      //var instance = new RemoteflagsNodejsClient.UsageRequestInner();
      //expect(instance).to.be();
    });

  });

}));
