/**
 * Remote Flags API
 * Remote Flags openapi definition. Public readonly API for integration with Remote Flags.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@remoteflags.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Status from './com.remoteflags.model/Status';
import PublicApi from './com.remoteflags.api/PublicApi';


/**
* Remote_Flags_openapi_definition__Public_readonly_API_for_integration_with_Remote_Flags_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RemoteflagsNodejsClient = require('index'); // See note below*.
* var xxxSvc = new RemoteflagsNodejsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RemoteflagsNodejsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RemoteflagsNodejsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RemoteflagsNodejsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Status model constructor.
     * @property {module:com.remoteflags.model/Status}
     */
    Status,

    /**
    * The PublicApi service constructor.
    * @property {module:com.remoteflags.api/PublicApi}
    */
    PublicApi
};
